SELECT *
FROM (
(
    SELECT SUBSTRING(SALES_DATE,1) AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
)
UNION
(
SELECT SUBSTRING(SALES_DATE,1) AS SALES_DATE, PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM ONLINE_SALE 
)) A
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
