SELECT C.ANIMAL_ID, C.NAME
FROM (
SELECT A.ANIMAL_ID, A.NAME, DATEDIFF(B.DATETIME,A.DATETIME) AS DATETIME
    FROM ANIMAL_INS A
    JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    ORDER BY DATETIME DESC
) C
LIMIT 2
