SELECT B.YEAR, B.MONTH, A.GENDER, COUNT(DISTINCT(A.USER_ID)) USERS
FROM USER_INFO A
JOIN
(SELECT USER_ID, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH
FROM ONLINE_SALE) B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY B.YEAR, B.MONTH, A.GENDER
ORDER BY B.YEAR, B.MONTH, A.GENDER ASC