# -- 코드를 작성해주세요

# SELECT a.ID, b.FISH_NAME, a.LENGTH
# FROM (
#     SELECT c.ID, c.FISH_TYPE, MAX(c.LENGTH) AS LENGTH
#     FROM FISH_INFO c
#     GROUP BY c.ID, c.FISH_TYPE
#     ORDER BY LENGTH DESC
#     LIMIT 1
# ) a
# JOIN FISH_NAME_INFO b on a.FISH_TYPE = b.FISH_TYPE
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE A.LENGTH = (
    SELECT MAX(C.LENGTH)
    FROM FISH_INFO C
    WHERE A.FISH_TYPE = C.FISH_TYPE
)